const projects = [
  {
    id: 0,
    type: "React JS",
    title: "NJOHFOLIO",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["react", "laravel", "php", "tailwind", "html", "js"],
    image: "/assets/images/template.webp",
    github: "https://github.com/njohjunior/Livraison-Frontend",
    demo: "https://livraison-frontend.vercel.app/",
  },
  {
    id: 1,
    type: "wordpress",
    title: "FIGURATIVE",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://figurative.fr",
  },
  {
    id: 2,
    type: "wordpress",
    title: "OEIL-SUR",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://oeil-sur.com",
  },
  {
    id: 3,
    type: "wordpress",
    title: "SYNERGIE BARBER",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://synergie-barber.com",
  },
  {
    id: 4,
    type: "wordpress",
    title: "CJARC",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://cjarc.org",
  },
  {
    id: 5,
    type: "wordpress",
    title: "CMICJARC",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://cmicjarc.com",
  },
  {
    id: 6,
    type: "wordpress",
    title: "IMMIGRATION LAFINESSE",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["wordpress", "elementor", "php", "css", "html", "js"],
    image: "/assets/images/template.webp",
    github: "/#",
    demo: "https://immigration-lafinesse.com",
  },
  {
    id: 7,
    type: "React - Laravel",
    title: "LE POINT DELIVERY",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    technologies: ["react", "laravel", "php", "tailwind", "html", "js"],
    image: "/assets/images/template.webp",
    github: "https://github.com/njohjunior/Livraison-Frontend",
    demo: "https://livraison-frontend.vercel.app/",
  },
];

export default projects;
